// src/app/features/compare-titles/title-item/title-item.component.ts
import { DatePipe } from '@angular/common';
import { Component, input, output, signal } from '@angular/core';

import { MediaItem } from '../../../core/models/title.model';

@Component({
  selector: 'app-title-item',
  imports: [DatePipe],
  template: `
    @if (!displayOnly()) {
    <div class="item" (click)="handleSelection()">
      <div class="item_poster_wrapper">
        <img
          class="item_poster"
          (load)="onImageLoad()"
          [src]="item()?.posterUrl"
          alt="{{ item()?.name }}"
          [class.loaded]="imageLoaded"
        />
      </div>
      <div>
        <h3>{{ item()?.name }} ({{ item()?.releaseDate | date : 'yyyy' }})</h3>
        <p class="item_overview">{{ item()?.overview }}</p>
      </div>
    </div>
    } @if (displayOnly()) {
    <div class="item display-only">
      <div
        class="item_poster_wrapper"
        (mouseenter)="handleHover($event)"
        (mouseleave)="handleHover($event)"
      >
        @if (hovered()) {
        <div (click)="handleRemoval()" class="item_poster_overlay">
          <p>Click to</p>
          <p>Remove</p>
        </div>
        }
        <img
          class="item_poster"
          [class.loaded]="imageLoaded"
          (load)="onImageLoad()"
          [src]="item()?.posterUrl"
          [alt]="item()?.name"
        />
      </div>
    </div>
    }
  `,
  styleUrl: './title-item.component.scss',
})
export class TitleItemComponent {
  itemSelected = output<MediaItem>();
  itemRemoved = output<MediaItem>();
  item = input<MediaItem | null>(null);
  displayOnly = input<boolean>();
  imageLoaded = false;
  hovered = signal(false);

  public handleSelection() {
    const selectedItem = this.item();
    if (selectedItem) this.itemSelected.emit(selectedItem);
  }

  public handleRemoval() {
    const selectedItem = this.item();
    if (selectedItem) this.itemRemoved.emit(selectedItem);
  }

  public onImageLoad() {
    this.imageLoaded = true;
  }

  public handleHover(e: MouseEvent) {
    e.type === 'mouseenter' ? this.hovered.set(true) : this.hovered.set(false);
  }
}

// app/components/title-item/title-item.tsx
"use client"

import Image from 'next/image';
import './title-item.scss';
import { MediaItem } from '@/app/models/api.model';
import { useState } from 'react';

interface TitleItemProps {
  item: MediaItem;
  posterOnly?: boolean;
  onTitleSelect?: (item: MediaItem) => void;
  onTitleRemove?: (item: MediaItem) => void;
}

const TitleItem = ({ item, posterOnly = false, onTitleSelect, onTitleRemove }: TitleItemProps) => {
  const [hovered, setHovered] = useState(false);
  const [loaded, setLoaded] = useState(false);

  const handleHover = (e: React.MouseEvent<HTMLDivElement, MouseEvent>) => {
    setHovered(e.type === "mouseenter");
  }

  return posterOnly ? (
    <div className="item display-only">
      <div
        className="item_poster_wrapper"
        onMouseEnter={handleHover}
        onMouseLeave={handleHover}
      >
        {hovered && (
          <div className="item_poster_overlay" onClick={() => onTitleRemove?.(item)}>
            <p>Click to</p>
            <p>Remove</p>
          </div>
        )}
        <Image
          onLoad={({ currentTarget }) => {
            if (currentTarget.complete) {
              setLoaded(true);
            }
          }}
          className={`item_poster ${loaded ? "loaded" : ""}`}
          src={item.posterUrl}
          height={90}
          width={50}
          alt="poster"
        />
      </div>
    </div>
  ) : (
    <div className="item" onClick={() => onTitleSelect?.(item)}>
      <div className="item_poster_wrapper">
        <Image
          onLoad={({ currentTarget }) => {
            if (currentTarget.complete) setLoaded(true);
          }}
          className={`item_poster ${loaded ? "loaded" : ""}`}
          src={item.posterUrl}
          height={90}
          width={50}
          alt="poster"
        />
      </div>
      <div>
        <h3>{item.name} ({new Date(item.releaseDate).getFullYear()})</h3>
        <p className="item_overview">{item.overview}</p>
      </div>
    </div>
  );
}

export default TitleItem;
